services:
  - type: web
    name: sims-iot-microservice
    env: docker
    dockerContext: ./server
    dockerfilePath: server/Dockerfile # Añadimos la ruta exacta al archivo
    plan: free
    envVars:
      - key: IOT_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: cluster-iot
